# For more information: https://laravel.com/docs/sail
version: '3'
services:
  mysql:
    image: 'mariadb:10.6'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'referral_factory_encryption'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './data/mysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  nginx:
    build:
      context: "./docker/nginx"
    image: 'referral-factory/encryption-nginx:v3'
    depends_on:
      - php-fpm
    volumes:
      - ./data/app:/var/www/html:cached
      - ./docker/nginx/sites:/etc/nginx/sites-available
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - sail

  php-fpm:
    build:
      context: "./docker/php-fpm"
    image: 'referral-factory/encryption-php-fpm:v3'
    environment:
      REPO_PULL_TOKEN: '${REPO_PULL_TOKEN}'
    volumes:
      - ./data/app:/var/www/html:cached
    networks:
      - sail
    expose:
      - "9000"

  laravel-horizon:
    build:
      context: ./docker/laravel-horizon
    volumes:
      - ./data/app:/var/www/html
      - ./docker/laravel-horizon/supervisord.d:/etc/supervisord.d
    depends_on:
      - php-fpm
    networks:
      - sail

networks:
  sail:
    driver: bridge
volumes:
  sail-redis:
    driver: local